name: ChatFeelings
main: com.zachduda.chatfeelings.Main
website: https://zachduda.com/chatfeelings
author: zach_attack
version: 5.0.0-BETA2
api-version: 1.21
softdepend: [Essentials, VanishNoPacket, LiteBans, AdvancedBan, PlaceholderAPI]
description: Allow your players to show their love, or hatred, with unique emotes!
folia-supported: true
commands:
  chatfeelings:
    description: General command for chatfeelings.
    aliases: [ cf ]
  feelings:
    description: Lists all the feelings you can do!
    aliases: [ emotions ]