General:
  Global-Feelings:
    Enabled: false
    Broadcast-To-Console: true
  Prevent-Self-Feelings: true
  Violent-Command-Harm: true
  Cooldowns:
    Feelings:
      Enabled: true
      Seconds: 10
    Ignoring:
      Enabled: true
      Seconds: 5
    Ignore-List:
      Enabled: true
      Seconds: 10
  Radius:
    Enabled: false
    Radius-In-Blocks: 35    
  Particles: true
  Sounds: true
  Extra-Help: true
  Use-Feeling-Permissions: false
  Disabled-Sending-Worlds: []
  Disabled-Receiving-Worlds:
  - world_the_end
  Multi-Version-Support: false
  Use-Nickname-Placeholder: false
  Nickname-Placeholder: "%essentials_nickname%"
  Help-Page-Length: 6
Other:
  Vanished-Players:
    Check: true
    Use-Legacy: false
  Player-Files:
    Cleanup: true
    Cleanup-After-Days: 185
    Erase-If-Banned: true
  Updates:
    Check: true
  Metrics: true
  Debug: false
  Reduce-Console-Msgs: false
LVU: "" # Do not touch
Version: 7 # Do not touch