name: ChatFeelings
main: com.zachduda.chatfeelings.Main
website: https://zachduda.com/chatfeelings
authors: [zach_attack]
version: 4.15-B75
api-version: 1.13
softdepend: [Essentials, VanishNoPacket, LiteBans, AdvancedBan, PlaceholderAPI]
description: Allow your players to show their love, or hatred, with unique emotes!
folia-supported: true
commands:
  chatfeelings:
    description: General command for chatfeelings.
  feelings:
    description: Lists all the feelings you can do!
    aliases: [ emotions ]
  hug:
    description: Gives somebody a nice warm hug!
  slap:
    description: Slap some sense back into someone.
  poke:
    description: Poke someone to get their attention.
  highfive:
    description: Show your support, and give a highfive!
  facepalm:
    description: Need to show some disapproval?
  yell:
    description: Yell at someone as loud as possible!
  bite:
    description: Bite a player right on the arm.
  snuggle:
    description: Snuggle up with the power of warm hugs!
  shake:
    description: Shakes a player to their feet.
  stab:
    description: Stab someone with a knife. Ouch!
  kiss:
    description: Make sweet sweet love. uwu
  punch:
    description: Punch the lights out of someone!
  murder:
    description: Finna kill someone here.
  boi:
    description: Living in 2016? Boi at a player.
  cry:
    description: Real sad hours? Cry at a player.
  dab:
    description: Freshly dab on someone.
  lick:
    description: Lick someone like an ice-cream sundae!
  scorn:
    description: Shame a player for what they've done.
  pat:
    description: Pat a players head for being good.
  stalk:
    description: Stalk a player carefully... carefully.
  sus:
    description: Pure single-boned suspicion.
  wave:
    description: Say farewell, and wave aideu. How elegant!
  welcomeback:
    description: Give a warm welcome-back to returning players!
  boop:
    description: Boop someone right on their nose!
permissions:
  chatfeelings.*:
    description: Allows all ChatFeelings emotes, commands, including administrative actions.
    children:
      chatfeelings.admin: true
      chatfeelings.stats: true
      chatfeelings.stats.others: true
      chatfeelings.mute: true
      chatfeelings.ignore: true
      chatfeelings.bypasscooldowns: true
      chatfeelings.all: true
  chatfeelings.all:
    description: Allows access all ChatFeelings emotes.
    default: true
    children:
      chatfeelings.hug: true
      chatfeelings.slap: true
      chatfeelings.poke: true
      chatfeelings.highfive: true
      chatfeelings.facepalm: true
      chatfeelings.yell: true
      chatfeelings.bite: true
      chatfeelings.snuggle: true
      chatfeelings.shake: true
      chatfeelings.kiss: true
      chatfeelings.punch: true
      chatfeelings.murder: true
      chatfeelings.cry: true
      chatfeelings.boi: true
      chatfeelings.dab: true
      chatfeelings.lick: true
      chatfeelings.pat: true
      chatfeelings.stalk: true
      chatfeelings.sus: true
      chatfeelings.wave: true
      chatfeelings.welcomeback: true
      chatfeelings.boop: true
  chatfeelings.hug:
    default: true
  chatfeelings.slap:
    default: true
  chatfeelings.poke:
    default: true
  chatfeelings.highfive:
    default: true
  chatfeelings.facepalm:
    default: true
  chatfeelings.yell:
    default: true
  chatfeelings.bite:
    default: true
  chatfeelings.snuggle:
    default: true
  chatfeelings.shake:
    default: true
  chatfeelings.kiss:
    default: true
  chatfeelings.punch:
    default: true
  chatfeelings.murder:
    default: true
  chatfeelings.cry:
    default: true
  chatfeelings.boi:
    default: true
  chatfeelings.dab:
    default: true
  chatfeelings.lick:
    default: true
  chatfeelings.pat:
    default: true
  chatfeelings.stalk:
    default: true
  chatfeelings.sus:
    default: true
  chatfeelings.wave:
    default: true
  chatfeelings.welcomeback:
    default: true
  chatfeelings.boop:
    default: true
  chatfeelings.admin:
    default: op
  chatfeelings.stats:
    default: true
  chatfeelings.stats.others:
    default: op
  chatfeelings.mute:
    default: op
  chatfeelings.ignore:
    default: op
  chatfeelings.bypasscooldowns:
    default: op